### ISSUE TITLE
Plugin not supported anymore in pycharm 2021.1.1

### ISSUE THREAD

**Issue by desmese** [BlackStartx/PyCharm-Blender-Plugin#1]
Hi,
Your plugin looks very usefull. Unfortunately I get the following error when i try to install it in pycharm 2021.1.1:
_"Plugin 'Blend-Charm' (version '1.0') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PY-211.7142.13"_
I increased the intellij version that was targeted, and fixed some deprecation warnings. This allows the plugin to be installed under Pycharm 2021.1.1 as well. I will link my PR to this issue.

**Comment by BlackStartx** [comment]
Hi,

First of all, I'm really sorry for the late answer, I'm not used to have public and active repositories on GitHub, and I didn't get (or probably didn't see) the pull requests or issue notification.
By the way, I'll definetly pull and release a new version soon with a bounce of new feature as well.
Thanks for the fixes.

And... Thank you so much for using the plugin ♥

**Comment by desmese** [comment]
Hi,

No problem. Thanks for merging it and creating this plugin.
It makes it a lot easier to start developing blender plugins.
Looking forward to the new version!

________________________________
