### ISSUE TITLE
Plugin does not want to install PyCharm 2023.1 and 2023.2 Community's Edition

### ISSUE THREAD

**Issue by WakaKrazyBerry** [BlackStartx/PyCharm-Blender-Plugin#19]
I have tried installing the Plugin on 2023.1 and 2023.2 and keep getting "Fail to load plugin descriptor from file (then Plugin Name)"
![pycharm64_BT6ukwRc3U](https://github.com/BlackStartx/PyCharm-Blender-Plugin/assets/61536544/559f1b62-ed4d-41ef-bf59-ab7bf9b7cc72)

I dont know if I am doing something wrong but have tried extracting and putting it in plugin folder still does not want to work mind assisting thank you

**Comment by BlackStartx** [comment]
Hi Waka~

Are you following the instruction in the [Manual Installation](https://github.com/BlackStartx/PyCharm-Blender-Plugin#manual-installation) section of the ReadMe?

It's not required to extract the content form the downloaded .zip file, you need to use the "Install Plugin from Disk..." feature from within the IDEE itself~

![](https://raw.githubusercontent.com/BlackStartx/PyCharm-Blender-Plugin/main/MarkDown/Img/Install.png)

Have you tried this way?

**Comment by WakaKrazyBerry** [comment]
Yep I have tried that and gives me the same error 

Also thank you for the Replay XD

**Comment by MateosCz** [comment]
I have the same issue as you, did you find any solutions?

**Comment by WakaKrazyBerry** [comment]
Hay

Sorry for taking so long to replay was away for quite some time I am
running Windows 11
I will do some more test my side maybe I am just doing something wrong

**Comment by WakaKrazyBerry** [comment]
Okay So I tried a reinstall and placing the files in different locations
and also running it as administrator also tried looking for similar
problems online and still doing the same thing

Any suggestions?

**Comment by WakaKrazyBerry** [comment]
Okay well I feel so dumb right now okay I am used to download it here and like this 

![vivaldi_HJAv0owoIv](https://github.com/BlackStartx/PyCharm-Blender-Plugin/assets/61536544/c3366af2-e307-499e-8372-8b79cdfa593e)


But you should go top left main ->tags -> View all Tags -> Next to the Version you want there will be a "Downloads" Click that and then select community or Professional 
![vivaldi_zKpq1OxUpT](https://github.com/BlackStartx/PyCharm-Blender-Plugin/assets/61536544/a493f86d-afd1-49f6-af45-bc113cda8d2a)

That works just use that file then sorry I feel like I was being dumb but that works XD

**Comment by BlackStartx** [comment]
Oh, I see~ ^-^ 🌺
Knowing this, the error now makes sense! ahahah

Thanks for sharing what the issue was.
I'm sure that other people may also download the non-builded zip file and I'll be able to help them easier in the future! :3
