### ISSUE TITLE
Blender 4.0 Crash

### ISSUE THREAD

**Issue by Doomerdinger** [BlackStartx/PyCharm-Blender-Plugin#20]
After the update to blender 4.0 when I attempt to run blender from the plugin I get the following error:

`blender: ../external_epoxy/src/dispatch_common.c:872: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.`

I am running the plugin on Ubuntu 20. I have a tweaked build of the plugin to get it to work properly, but the changes are fairly minor and it worked fine with blender 3.6.

Can anyone confirm if the plugin continues to work (or not) on officially supported operating systems?

**Comment by BlackStartx** [comment]
Hi Doomerdinger~ 🌺

I just downloaded and run my tool with Blender 4.0.0 and it's indeed working as intended on Windows OS.

From a research it seems a common problem on Linux-based OS, I'm sorry for not beeing more helpful~ :c

**Comment by Doomerdinger** [comment]
That's helpful to know, thank you!
I'll try tinkering on my end. If I figure it out I'll update the thread.

**Comment by Doomerdinger** [comment]
After the most recent blender update my build actually seems to work again. :woman_shrugging:
