### ISSUE TITLE
Pycharm 2024.1 says 'Blend-Charm' plugin is no longer compatible

### ISSUE THREAD

**Issue by eriklundh** [BlackStartx/PyCharm-Blender-Plugin#24]
Pycharm error message:
Plugin 'Blend-Charm' (version '2023.3') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is PY-241.14494.241

**Comment by BlackStartx** [comment]
Hi Erik~ 🌺

I've just released the new 2024.1 version of my tool, sorry for the delay~ ^-^

Feel free to re-open the issue if anything goes wrong!
