### ISSUE TITLE
PyCharm does not recognize Blender's built-in libraries

### ISSUE THREAD

**Issue by Shararamosh** [BlackStartx/PyCharm-Blender-Plugin#27]
Actually for some reason it does not even recognize bpy, which is installed through pip.
![image](https://github.com/user-attachments/assets/7b29d54e-2240-4622-b9c6-c18c414e26e0)

**Comment by louhy** [comment]
I just installed fake-bpy-module-latest under Settings->Project: [...]->Python Interpreter and the errors I was seeing went away.
