### ISSUE TITLE
PyCharm installation error: Fail to load plugin descriptor from file

### ISSUE THREAD

**Issue by GrasSoft** [BlackStartx/PyCharm-Blender-Plugin#28]
I have tried to install the repository .zip file and received this error:

![image](https://github.com/user-attachments/assets/703cdd7e-9605-4389-bf45-dde6b1764eae)

**Comment by BlackStartx** [comment]
Have you downloaded the whole repository as a zip file?

The package you have to instal trough the Addon page can be found in the release tab! ^-^ 🌺

**Comment by GrasSoft** [comment]
I have not, was not really aware of this feature. Thank you so much!

**Comment by GrasSoft** [comment]
I have not, was not really aware of this feature. Thank you so much!

**Comment by GrasSoft** [comment]
Hello,

I did not want to open another useless issue. After I install the plugin, I find it difficult to find the executable with the in place path finder.

No biggie. I copied the path myself. But I can not seem to find a way to actually start blender from PyCharm

Thank you for your help.





________________________________

**Comment by BlackStartx** [comment]
Are you on MacOS?

**Comment by GrasSoft** [comment]
Linux

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
