### ISSUE TITLE
print nothing

### ISSUE THREAD

**Issue by MoConWu** [BlackStartx/PyCharm-Blender-Plugin#4]
when print i got nothing

and when closed blender, i got that

**Comment by MoConWu** [comment]
used debug

**Comment by BlackStartx** [comment]
Hi MoConWu~

Yes... sadly the **print** function in the run or debug console is currently a little buggy,
Right now, the workarround is to use the python logging library.
 
The output should work way better, and it works in both run or debug console.

Example:
```py
import logging

logging.log(logging.INFO, "Hello World!")
```

Sorry for the issue,

\- BlackStartx

**Comment by MoConWu** [comment]
Hi，I can get log.WARNING/ERROR
but not get log.INFO

Where can set show level, THANKS
